name: resource_checker
description: Resource checker - given the asset path checks if it is valid
version: 0.1.0
homepage: https://github.com/spirifoxy/resource_checker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

